language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - sudo apt-get install -qq gdb python-all-dbg
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install coveralls --use-mirrors && export HAS_COVERALLS=1; fi

script:
  - nosetests -v --with-coverage --cover-erase --cover-package=pyrasite

after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi

notifications:
  irc: "chat.freenode.net#pyrasite"
